### ISSUE TITLE
[12.0] bi_view_editor: row_number over () does not guarantee ordering

### ISSUE THREAD

**Issue by SimoRubi** [OCA/reporting-engine#388]
Hi,
given the following view created using module `bi_view_editor`:
```
CREATE OR REPLACE VIEW public.x_bve_commissioni
AS SELECT row_number() OVER ()::integer AS id,
    t1.id AS x_bve_t1_id, -- manually added for analysis
    t1.agent_id AS x_bve_t1_agent_id,
    t1.partner_id AS x_bve_t1_partner_id,
    t1.date_invoice AS x_bve_t1_date_invoice,
    t1.product_id AS x_bve_t1_product_id,
    t1.price_unit AS x_bve_t1_price_unit,
    t1.commission_id AS x_bve_t1_commission_id,
    t1.price_subtotal_signed AS x_bve_t1_price_subtotal_signed,
    t1.amount AS x_bve_t1_amount
   FROM sale_commission_analysis_report t1; -- defined in https://github.com/OCA/commission/blob/befb9470a352edc9a2946bbf1c3b5a57e02badeb/sale_commission/report/sale_commission_analysis_report.py#L7
```
I am currently encountering the following strange behavior:
```
prod_db=# select * from x_bve_commissioni where id = 5130;
  id  | x_bve_t1_id | x_bve_t1_agent_id | x_bve_t1_partner_id | x_bve_t1_date_invoice | x_bve_t1_product_id |  x_bve_t1_price_unit   | x_bve_t1_commission_id | x_bve_t1_price_subtotal_signed | x_bve_t1_amount 
------+-------------+-------------------+---------------------+-----------------------+---------------------+------------------------+------------------------+--------------------------------+-----------------
 5130 |       36303 |             14343 |               19833 | 2020-03-16            |                   2 | 0.00000000000000000000 |                     11 |                           0.00 |            0.00
(1 row)

prod_db=# select id, x_bve_t1_id,  x_bve_t1_date_invoice from x_bve_commissioni where id = 5130;
  id  | x_bve_t1_id | x_bve_t1_date_invoice 
------+-------------+-----------------------
 5130 |       19991 | 2020-01-27
(1 row)
```
I expect the column `x_bve_t1_id` to be the same in both query results.

I'm no PostgreSQL expert but I did some research and the solution I came up with is adding an `order by t1.id` clause in the `OVER` of  column `row_number() OVER ()::integer AS id`.
I've seen that the column's creation is hardcoded in https://github.com/OCA/reporting-engine/blob/124d1db26b3f13f3b4669896699a4b9f3e16eb49/bi_view_editor/models/bve_view.py#L292 so I don't really know how this could be fixed.

Any ideas?
Thanks!

**Comment by SimoRubi** [comment]
Update: this issue may be related to creating view on other view.
In our instance we managed to create another _faulty_ view on model **sale_report**, I can't manage to reproduce the issue in runbot though.

**Comment by legalsylvain** [comment]
Hi. I introduced the id with row number to be sure to have a valid unique ID on each row of each model. It is (or was) required by the odoo ORM.
I don't think thought that this ID can be used for anything, as the distribution is made randomly, or is not predictive.
Why do you need to make a request ``where id = xxx `` ?

**Comment by legalsylvain** [comment]
Sorry my bad. I thought that you was talking about bi sql editor module (that implement similar concept). My answer is maybe not valid in that context.
Kind regards.

**Comment by SimoRubi** [comment]
Thanks for your answers anyway :)

> Why do you need to make a request `where id = xxx `?

Everything begins with creating the view described, then I tried to filter it by date: this is translated by the ORM in a query like:
```
SELECT "x_bve_commissioni".id 
FROM "x_bve_commissioni" 
WHERE ("x_bve_commissioni"."x_bve_t1_date_invoice" = '2020-03-23')
ORDER BY "x_bve_commissioni"."id"   limit 80;
```
This returns a list of ids (in our instance `109, ...`), but the rows having those ids do NOT have `"x_bve_t1_date_invoice" = '2020-03-23'`.

In fact
```
SELECT "x_bve_commissioni".* 
FROM "x_bve_commissioni" 
WHERE ("x_bve_commissioni"."x_bve_t1_date_invoice" = '2020-03-23')
ORDER BY "x_bve_commissioni"."id"   limit 80;
```
returns rows having other ids (in our instance `19, ...`).

**Comment by legalsylvain** [comment]
Whow ! It's very weird ! Never had this problem with ``bi_sql_editor`` I use since 4 years and that implements similar ID generation mechanism.
Sorry no idea how to fix it. kind regards.

**Comment by richard-willdooit** [comment]
I would like to add, that even if you order by, you may end up with a different id if you look at the data at a different time - you can only rely on the id within the transaction.

This is true when a row may be inserted or removed from the view ...

This should not have happened in your instance, as far as I can tell, but:

When I use "SELECT row_number() OVER ()::integer AS id,", and I want to rely on the ids, I always put an "order by " clause in to be 100% sure that it will get the same rows for the same data.  Otherwise, it cannot be guaranteed.  Even on the same data.

If you are still having problems, I would use pgadmin or somesuch, and look at your data, and the ids, and check it is behaving exactly as you expect.

`prod_db=# select * from x_bve_commissioni where id = 5130;
  id  | x_bve_t1_id | x_bve_t1_agent_id | x_bve_t1_partner_id | x_bve_t1_date_invoice | x_bve_t1_product_id |  x_bve_t1_price_unit   | x_bve_t1_commission_id | x_bve_t1_price_subtotal_signed | x_bve_t1_amount 
------+-------------+-------------------+---------------------+-----------------------+---------------------+------------------------+------------------------+--------------------------------+-----------------
 5130 |       36303 |             14343 |               19833 | 2020-03-16            |                   2 | 0.00000000000000000000 |                     11 |                           0.00 |            0.00
(1 row)

prod_db=# select id, x_bve_t1_id,  x_bve_t1_date_invoice from x_bve_commissioni where id = 5130;
  id  | x_bve_t1_id | x_bve_t1_date_invoice 
------+-------------+-----------------------
 5130 |       19991 | 2020-01-27
(1 row)`

Remember, these are separate transactions, and your second select statement will have at some level been optimised and removed some data from consideration, thereby behaving differently.  I am confident an order by that guarantees a unique sequence will sort that.
