### ISSUE TITLE
[14.0] report_py3o print error

### ISSUE THREAD

**Issue by rbellanova** [OCA/reporting-engine#789]
Hello when I'm printing a report (eg. account invoice report) in odt format as showed on manifest, I get an error "_display_report_header" is missing on res.company.

This function is present on "base_usability" module that is missing in OCA modules, it is a module of akretion "odoo-usability" repository: https://github.com/akretion/odoo-usability/tree/14.0/base_usability

**Comment by legalsylvain** [comment]
CC : original contributors : lmignon, @omar7r, @hbrunn, @alexis-via 
Could you take a look here ? 
thanks !

**Comment by len-foss** [comment]
Isn't this because you're trying with examples from https://github.com/akretion/odoo-py3o-report-templates?
If that's the case there are other dependencies from https://github.com/akretion/odoo-usability in these report; for instance `sale_report_py3o` lists the following:  
```
'depends': [
        'report_py3o',
        'sale_commercial_partner',
        'base_company_extension',
        'base_usability',  # to have res_partner.name_title
        'sale_usability',  # for layout
        'account_payment_sale',
        ],
```
Which does include base_usability.
