### ISSUE TITLE
[Q] Visualisation of streaming data/anomaly highlighting

### ISSUE THREAD

**Issue by breznak** [OCA/reporting-engine#79]
Hello, 

this is a follow-up to https://github.com/OCA/vertical-medical/issues/65#issuecomment-253952976 

Where I introduce  https://github.com/nupic-community/nupic.visualizations as an interactive visualization tool for streaming data, monitoring and anomaly highlighting. 
I'm wondering if the functionality could be any helpful for your projects? 

The visualization is done "in browser", the only requirement is: 
- `Node.js` if you want to run locally (which is already a dependency of your projects) 
- or none, if one doesn't mind sending the data over the internet to our hosted online instance. 

I'm not sure if we currently support a direct data feed (like REST?), instead of a file input, but that feature is planned and could be implemented. 

Please let me know your opinions, 
Cheers, 
Mark

**Comment by pedrobaeza** [comment]
@lasley, have you seen this interesting? Anyone else?

**Comment by lasley** [comment]
Ah yes I meant to drop a comment in this issue after it was switched from vertical-medical. 

I think this would be pretty neat if we were to have these visualizations integrated for reporting. This system just takes in any CSV for the most part, so we could piggy-back on top of our pre-existing export system to provide a "Visualize" option instead.

I admittedly forgot about this, so that was about the extent of my playing. It would be nicer I think if we could feed data directly without the CSV intermediary, which was about where I got before I forgot. I tossed an investigation ticket into my next sprint, but it would be interesting to see if anyone else had some thoughts on this.
