### ISSUE TITLE
report_py3o in Odoo.sh

### ISSUE THREAD

**Issue by odooNextev** [OCA/reporting-engine#792]
Hi all,
we'd like to install `report_py3o` in Odoo.sh, but as happens in other restrictive environments, we cannot install apt package.
Odoo support told us to find an alternative solution, for example using a pip package instead of apt, but we can't find a Libreoffice pip package.

Is it possible to find a solution using only pip packages?

**Comment by len-foss** [comment]
There isn't any way to get arbitrary binaries into Python packages. If you need the feature on a .sh instance, you would need to make it so that instead of calling a local libreoffice, it would call another server running libreoffice. There is `report_py3o_fusion_server` that does exactly that. But that does require you to deploy and maintain a server.

**Comment by odooNextev** [comment]
@len-foss thanks a lot, it can be a solution.
